version: "3"
services:
  bot_app:
    container_name: bot_app
    build: .
    ports:
        - "8080:8080"
  web:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./app:/usr/share/nginx/html
