version: "3.1"
services:
  reverse:
    container_name: reverse
    hostname: reverse
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certs:/etc/ssl/private
  bot_app:
    container_name: bot_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081